version: '3.8'

services:
  server-monitor:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - DATABASE_PATH=/app/data/servers.db
    restart: unless-stopped
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge

volumes:
  monitor-data: